name: Build e Publicar no NuGet

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restaurar dependências
      run: dotnet restore src/DeadSharp.sln
    
    - name: Build
      run: dotnet build src/DeadSharp.sln --configuration Release --no-restore
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restaurar dependências
      run: dotnet restore src/DeadSharp.sln
    
    - name: Build
      run: dotnet build src/DeadSharp.sln --configuration Release --no-restore
    
    - name: Criar pacote NuGet
      run: dotnet pack src/DeadSharp.csproj --configuration Release --output ./nupkg
    
    - name: Publicar no NuGet.org
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    - name: Configurar GitHub Packages
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      
    - name: Publicar no GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate 