name: Build e Publicar no NuGet

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restaurar dependências
      run: dotnet restore src/DeadSharp.sln
    
    - name: Build
      run: dotnet build src/DeadSharp.sln --configuration Release --no-restore
      
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restaurar dependências
      run: dotnet restore src/DeadSharp.sln
    
    - name: Build
      run: dotnet build src/DeadSharp.sln --configuration Release --no-restore
    
    - name: Obter versão da tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Criar pacote NuGet
      run: dotnet pack src/DeadSharp.csproj --configuration Release --output ./nupkg -p:Version=${{ steps.get_version.outputs.VERSION }}
    
    - name: Publicar no NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate 